using System.Collections;
using UnityEngine;

public class jogrginhoActivator : MonoBehaviour
{
    public GameObject Jorginho; // Objeto fantasma que ser치 ativado
    public AudioSource audioSource; // Fonte de 치udio para tocar o som

    private void OnTriggerEnter(Collider other)
    {
        // Verifica se o objeto que colidiu tem a tag "Player"
        if (other.CompareTag("Player"))
        {
            // Ativa o objeto fantasma
            Jorginho.SetActive(true);

            // Toca o som
            if (audioSource != null)
            {
                audioSource.Play();
            }

            // Inicia a corrotina para desativar o objeto ap칩s 2.5 segundos
            StartCoroutine(DeactivateAfterTime(2.5f));
        }
    }

    // Corrotina para desativar o objeto ap칩s um tempo
    private IEnumerator DeactivateAfterTime(float time)
    {
        yield return new WaitForSeconds(time); // Espera o tempo especificado
        Jorginho.SetActive(false); // Desativa o objeto
    }
}
